"""add superuser

Revision ID: 44708acf6ab4
Revises: cf9bdef04041
Create Date: 2023-06-12 19:23:09.853822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44708acf6ab4'
down_revision = 'cf9bdef04041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
